### ISSUE TITLE
Alicloud plugin cause Terraform crash

### ISSUE THREAD

**Issue by lansz** [alibaba/terraform-provider#107]
Crash log as following:
```
terraform refresh
alicloud_vpc.mycompany_dev_vpc: Refreshing state... (ID: vpc-2zexc...9edmqyt6)
alicloud_security_group.dev-depta-backend: Refreshing state... (ID: sg-2ze0jl...z5xcx8oa)
alicloud_security_group.dev-depta-database: Refreshing state... (ID: sg-2zehfs...f90ixx29)
alicloud_security_group_rule.depta-backend-to-database_mysql: Refreshing state... (ID: sg-2zehfs...intranet)
Error refreshing state: 1 error(s) occurred:

* alicloud_security_group_rule.depta-backend-to-database_mysql: alicloud_security_group_rule.depta-backend-to-database_mysql: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
2017/03/29 19:30:27 [DEBUG] plugin: terraform: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16f8399]
2017/03/29 19:30:27 [DEBUG] plugin: terraform:
2017/03/29 19:30:27 [DEBUG] plugin: terraform: goroutine 40 [running]:
2017/03/29 19:30:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/builtin/providers/alicloud.resourceAliyunSecurityGroupRuleRead(0xc4203035e0, 0x57f2600, 0xc420533d80, 0x0, 0x8108380)
2017/03/29 19:30:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/builtin/providers/alicloud/resource_alicloud_security_group_rule.go:145 +0x529
2017/03/29 19:30:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc42029dd40, 0xc4208460f0, 0x57f2600, 0xc420533d80, 0xc4203aebe0, 0xc420986901, 0xc420047a88)
2017/03/29 19:30:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/resource.go:314 +0x21d
2017/03/29 19:30:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc420303500, 0xc4208460a0, 0xc4208460f0, 0x93bb960, 0x0, 0xc420886230)
2017/03/29 19:30:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/helper/schema/provider.go:267 +0x91
2017/03/29 19:30:27 [DEBUG] plugin: terraform: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc4201be960, 0xc4201c6130, 0xc4201c63a0, 0x0, 0x0)
2017/03/29 19:30:27 [DEBUG] plugin: terraform: 	/opt/gopath/src/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2017/03/29 19:30:27 [DEBUG] plugin: terraform: reflect.Value.call(0xc42032ce40, 0xc42017c040, 0x13, 0x58ac3de, 0x4, 0xc420047f20, 0x3, 0x3, 0x0, 0xc420a98930, ...)
2017/03/29 19:30:27 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:434 +0x91f
2017/03/29 19:30:27 [DEBUG] plugin: terraform: reflect.Value.Call(0xc42032ce40, 0xc42017c040, 0x13, 0xc42065c720, 0x3, 0x3, 0xc420467c80, 0x11fea73, 0xc420a50700)
2017/03/29 19:30:27 [DEBUG] plugin: terraform: 	/opt/go/src/reflect/value.go:302 +0xa4
2017/03/29 19:30:27 [DEBUG] plugin: terraform: net/rpc.(*service).call(0xc4204fa080, 0xc4204fa040, 0xc42049e2a0, 0xc420291500, 0xc4208f4220, 0x4b2f480, 0xc4201c6130, 0x16, 0x4b2f4c0, 0xc4201c63a0, ...)
2017/03/29 19:30:27 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:387 +0x144
2017/03/29 19:30:27 [DEBUG] plugin: terraform: created by net/rpc.(*Server).ServeCodec
2017/03/29 19:30:27 [DEBUG] plugin: terraform: 	/opt/go/src/net/rpc/server.go:481 +0x404
2017/03/29 19:30:27 [ERROR] root: eval: *terraform.EvalRefresh, err: alicloud_security_group_rule.depta-backend-to-database_mysql: unexpected EOF
2017/03/29 19:30:27 [ERROR] root: eval: *terraform.EvalSequence, err: alicloud_security_group_rule.depta-backend-to-database_mysql: unexpected EOF
2017/03/29 19:30:27 [TRACE] [walkRefresh] Exiting eval tree: alicloud_security_group_rule.depta-backend-to-database_mysql
2017/03/29 19:30:27 [DEBUG] plugin: /usr/local/Cellar/terraform/0.9.1_1/bin/terraform: plugin process exited
2017/03/29 19:30:27 [DEBUG] plugin: waiting for all plugin processes to complete...
2017/03/29 19:30:27 [WARN] plugin: error closing client during Kill: connection is shut down



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Reproduce steps as below:

1. Create a new tf file and apply it
```
resource "alicloud_vpc" "mycompany_dev_vpc" {
  name = "MY-DEV"
  cidr_block = "10.200.0.0/16"
}

resource "alicloud_security_group" "dev-depta-backend" {
    name = "dev-depta-backend"
    description = "DEV-DEPTA-BACKEND"
    vpc_id = "${alicloud_vpc.mycompany_dev_vpc.id}"
}
resource "alicloud_security_group" "dev-depta-database" {
    name = "dev-depta-database"
    description = "DEV-DEPTA-DATABASE"
    vpc_id = "${alicloud_vpc.mycompany_dev_vpc.id}"
}

resource "alicloud_security_group_rule" "depta-backend-to-database_mysql" {
  type = "ingress"
  ip_protocol = "tcp"
  nic_type = "intranet"
  policy = "accept"
  port_range = "3306/3306"
  priority = 50
  # description = "hahahahaha"
  security_group_id = "${alicloud_security_group.dev-depta-database.id}"
  source_security_group_id = "${alicloud_security_group.dev-depta-backend.id}"
}

```
2. Go to Aliyun web console, delete rule "depta-backend-to-database_mysql"
3. Run `terraform refresh` or `terraform apply` again and terraform crashs.

**Comment by heww** [comment]
this occurred for the `notFoundError` in `alicloud/common.go` not detected the resource not exist error. Some API of aliycloud return 200 for resource not found.

**Comment by demonwy** [comment]
@lansz  @heww 
Thanks for your report, You are both right.
We'll check nil ptr before use it. code in line [#135](https://github.com/alibaba/terraform-provider/blob/master/alicloud/resource_alicloud_security_group_rule.go#L135)

Thanks
Yue Wang

**Comment by demonwy** [comment]
@lansz  we have fixed it. I'm going to close this issue, but please let me know if you have any other questions or comments.

Thanks
